// <auto-generated />
using System;
using APBD_TECT_2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APBD_TECT_2.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20250609162420_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("APBD_TECT_2.DataLayer.Models.Race", b =>
                {
                    b.Property<int>("RaceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RaceId"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("RaceId");

                    b.ToTable("Races");

                    b.HasData(
                        new
                        {
                            RaceId = 1,
                            Date = new DateTime(2025, 6, 8, 18, 24, 19, 880, DateTimeKind.Local).AddTicks(8210),
                            Name = "Bulbozavr",
                            location = "Misnk"
                        },
                        new
                        {
                            RaceId = 2,
                            Date = new DateTime(2025, 5, 30, 18, 24, 19, 880, DateTimeKind.Local).AddTicks(8270),
                            Name = "Pikachi",
                            location = "Gomel"
                        });
                });

            modelBuilder.Entity("APBD_TECT_2.DataLayer.Models.RaceParticipation", b =>
                {
                    b.Property<int>("TrackRaceId")
                        .HasColumnType("int");

                    b.Property<int>("RacerId")
                        .HasColumnType("int");

                    b.Property<int>("FinishTimeInSeconds")
                        .HasColumnType("int");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.HasKey("TrackRaceId", "RacerId");

                    b.HasIndex("RacerId");

                    b.ToTable("RaceParticipation");

                    b.HasData(
                        new
                        {
                            TrackRaceId = 1,
                            RacerId = 1,
                            FinishTimeInSeconds = 10,
                            Position = 1
                        },
                        new
                        {
                            TrackRaceId = 2,
                            RacerId = 2,
                            FinishTimeInSeconds = 20,
                            Position = 2
                        });
                });

            modelBuilder.Entity("APBD_TECT_2.DataLayer.Models.Racer", b =>
                {
                    b.Property<int>("RacerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RacerId"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("RacerId");

                    b.ToTable("Racers");

                    b.HasData(
                        new
                        {
                            RacerId = 1,
                            FirstName = "Dmitry",
                            LastName = "Barmuta"
                        },
                        new
                        {
                            RacerId = 2,
                            FirstName = "Michal",
                            LastName = "Pazio"
                        },
                        new
                        {
                            RacerId = 3,
                            FirstName = "Danyil",
                            LastName = "Danilian"
                        },
                        new
                        {
                            RacerId = 4,
                            FirstName = "Oleksandr",
                            LastName = "Biktimirov"
                        });
                });

            modelBuilder.Entity("APBD_TECT_2.DataLayer.Models.Track", b =>
                {
                    b.Property<int>("TrackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrackId"));

                    b.Property<decimal>("LengthinKm")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("TrackId");

                    b.ToTable("Tracks");

                    b.HasData(
                        new
                        {
                            TrackId = 1,
                            LengthinKm = 100m,
                            Name = "Despacito"
                        },
                        new
                        {
                            TrackId = 2,
                            LengthinKm = 100m,
                            Name = "Despacito"
                        });
                });

            modelBuilder.Entity("APBD_TECT_2.DataLayer.Models.TrackRace", b =>
                {
                    b.Property<int>("TrackRaceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrackRaceId"));

                    b.Property<int>("BestTimeInSeconds")
                        .HasColumnType("int");

                    b.Property<int>("Laps")
                        .HasColumnType("int");

                    b.Property<int>("RaceId")
                        .HasColumnType("int");

                    b.Property<int>("TrackId")
                        .HasColumnType("int");

                    b.HasKey("TrackRaceId");

                    b.HasIndex("RaceId");

                    b.HasIndex("TrackId");

                    b.ToTable("TrackRace");

                    b.HasData(
                        new
                        {
                            TrackRaceId = 1,
                            BestTimeInSeconds = 1,
                            Laps = 1,
                            RaceId = 1,
                            TrackId = 1
                        },
                        new
                        {
                            TrackRaceId = 2,
                            BestTimeInSeconds = 10,
                            Laps = 2,
                            RaceId = 2,
                            TrackId = 2
                        });
                });

            modelBuilder.Entity("APBD_TECT_2.DataLayer.Models.RaceParticipation", b =>
                {
                    b.HasOne("APBD_TECT_2.DataLayer.Models.Racer", "Racer")
                        .WithMany("RaceParticipations")
                        .HasForeignKey("RacerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APBD_TECT_2.DataLayer.Models.TrackRace", "TrackRace")
                        .WithMany("RaceParticipations")
                        .HasForeignKey("TrackRaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Racer");

                    b.Navigation("TrackRace");
                });

            modelBuilder.Entity("APBD_TECT_2.DataLayer.Models.TrackRace", b =>
                {
                    b.HasOne("APBD_TECT_2.DataLayer.Models.Race", "Race")
                        .WithMany("TrackRaces")
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APBD_TECT_2.DataLayer.Models.Track", "Track")
                        .WithMany("TrackRaces")
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Race");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("APBD_TECT_2.DataLayer.Models.Race", b =>
                {
                    b.Navigation("TrackRaces");
                });

            modelBuilder.Entity("APBD_TECT_2.DataLayer.Models.Racer", b =>
                {
                    b.Navigation("RaceParticipations");
                });

            modelBuilder.Entity("APBD_TECT_2.DataLayer.Models.Track", b =>
                {
                    b.Navigation("TrackRaces");
                });

            modelBuilder.Entity("APBD_TECT_2.DataLayer.Models.TrackRace", b =>
                {
                    b.Navigation("RaceParticipations");
                });
#pragma warning restore 612, 618
        }
    }
}
